# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-11 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCrawlerJob', models.CharField(default=None, max_length=100)),
                ('codePost', models.IntegerField(default=None)),
                ('typePost', models.CharField(default=None, max_length=255)),
                ('title', models.TextField(default=None)),
                ('price', models.BigIntegerField(default=None)),
                ('area', models.DecimalField(decimal_places=5, default=None, max_digits=19)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(default=None)),
                ('numberBedrooms', models.IntegerField(default=None)),
                ('numberToilets', models.IntegerField(default=None)),
                ('sizeFront', models.BigIntegerField(default=None)),
                ('numberFloor', models.IntegerField(default=None)),
                ('wardin', models.BigIntegerField(default=None)),
                ('homeDirection', models.CharField(default=None, max_length=255)),
                ('balconyDirection', models.CharField(default=None, max_length=255)),
                ('interior', models.TextField(default=None)),
                ('longitude', models.BigIntegerField(default=None)),
                ('latitude', models.BigIntegerField(default=None)),
                ('nameOwner', models.CharField(default=None, max_length=255)),
                ('mobile', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('link', models.TextField(default=None)),
                ('projectName', models.CharField(default=None, max_length=255)),
                ('projectSize', models.TextField(default=None)),
                ('projectOwner', models.CharField(default=None, max_length=255)),
                ('startDatePost', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDatePost', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
