# Generated by Django 3.0.3 on 2020-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('area', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
        ),
    ]
