# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
