# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateobject',
            name='type',
            field=models.TextField(default=None),
        ),
    ]
