# Generated by Django 3.0.3 on 2020-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateobject',
            name='idCrawlerJob',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='idPost',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='typePost',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
