# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20200212_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateobject',
            name='idCrawlerJob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
