# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200212_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateobject',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
