# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200311_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateobject',
            name='sizeFront',
            field=models.DecimalField(decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='wardin',
            field=models.DecimalField(decimal_places=5, max_digits=19, null=True),
        ),
    ]
