# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20200311_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateobject',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=19, null=True),
        ),
    ]
