# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20200318_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
    ]
