# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-19 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='domain',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='domain',
            field=models.TextField(null=True),
        ),
    ]
