# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-24 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20200319_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealEstateObject',
            new_name='RealEstate',
        ),
    ]
